### PR TITLE
Use codecov.io

### PR DESCRIPTION
**Pull request by mattn**
I suggest to use codecov.io since it is easy to take coverage. Could you please create account of https://codecov.io ?

### CODE REVIEW

**Comment by owulveryck** [comment]
I have create the account on codeconv.io
The build fails with:
```
/home/travis/.travis/functions: line 104: ./go.test.sh: Permission denied
The command "./go.test.sh" exited with 126.
```

Maybe `chmod +x go.test.sh`?

**Comment by mattn** [comment]
Please look this. https://codecov.io/gh/owulveryck/onnx-go/pull/66/tree

**Comment by owulveryck** [comment]
codecov looks awesome!

**Comment by mattn** [comment]
There are no diffs since this is first commit. But will be displayed in next time.

**Comment by mattn** [comment]
Updated README.md. diffs will be displayed.

**Pull request merged**
