### PR TITLE
Add Constant operator

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by owulveryck** [comment]
Tanks for the PR.

The test fails because the test constant creates an empty graph which is not handled by Gorgonia (obviously).

The source of the failing test is:
https://github.com/owulveryck/onnx-go/blob/bcfed2a6f36b6ae4f6cab3570a7ae409262435eb/backend/testbackend/onnx/onnx_test_constant.go#L37 
which comes from this test https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node/test_constant

The problem is that the graph is composed of a single node which does not have any input. It is normal for a constant to not have any input, but an operator should. My opinion is that a constant should not be considered as an operator. the ONNX team seemed to disagree :D 

https://github.com/onnx/onnx/blob/master/docs/Operators.md#constant
 
I will investigate to see if it is something that can be easily fixed.

**Comment by mattn** [comment]
Probably, we can test ssd if onnx-go support constant and unsqueeze.

**Comment by owulveryck** [comment]
The official onnx project gave a reply to the [issue 2274](https://github.com/onnx/onnx/issues/2274) regarding the constant operator.

As expected, the IR will not change (indeed, It would have been a surprise that they change it for us). Therefore we may need to address this particular case.

Two other operators have the same behavior:
> Thus, RandomUniform and RandomNormal are two other examples of an operator with no inputs.

By now, I have no idea how to fix this in an idiomatic way.
My only idea is to detect those operators within the decodig process (in the [`decodeProto` method](https://github.com/owulveryck/onnx-go/blob/7c482d53bd0be130658c8ba3bbe3891d83087c21/decoder.go#L91)), and to turn them into initializers as mentioned in the original issue:
>There are "optimizer" passes that convert uses of "Constant" to replace it with an Initializer (just like you mention). 

WDYT?

**Comment by mattn** [comment]
So do you think Constant should always return empty?

**Comment by owulveryck** [comment]
TBH I don't know anymore. I thought we could do a particular case in the decoder to handle the "Constant operator" and turn it into an initializer. The Gorgonia's ExprGraph would have been valid and composed of a single node. But this will not work for the other input-less operators.

Another option is to fake an input by creating a new node of type `DataCarrier` in onnx-go's `*Model` structure if we detect a node that has no input. Then we attach this input to the operator to turn it into something valid.

The resulting graph would look like:

```text
   | NewInput with the |
   | Shape and type    |
   | of the Operator   |
   | `DataCarrier`     | 
           |
           |
           \/
   | Node Operation  |
   | OpType constant |
```
Then within Gorgonia, we create an operator that overwrites its input (see [the godoc of the Op interface](https://godoc.org/gorgonia.org/gorgonia#Op), the method should return 0).
This would not impact the performances and create a valid graph in all the cases.

I don't know if my explanation is clear enough, though. If it is not, I can try to quickly implement the `RandomNormal` operator as an illustration if you want. Let me know.

**Comment by owulveryck** [comment]
I have created issue #131 to follow the implementation as well as a branch.

**Comment by owulveryck** [comment]
Fix with [PR #132](https://github.com/owulveryck/onnx-go/pull/132)

**Pull request merged**
