### PR TITLE
refactor(internal/onnx/ir): rename internal/pb-onnx to internal/onnx/ir

### PR DESCRIPTION
**Pull request by rlespinasse**
In `internal/pb-onnx`, the package name is `pb` but the path ends `pb-onnx`, 

In order to improve maintainability, I propose 
* to change the path to `internal/onnx/<packagename>`,
* to rename it `ir` instead of `pb` to be compliant with the content (see @owulveryck comment)

### CODE REVIEW

**Comment by owulveryck** [comment]
TBH I don't see the need to rename the package.
`goimport` handles it very well by now.

On top of that, I don't think that `internal/onnx` will hold anything more than the `pb` package.
Anyway, it's an internal package, this would only impact the internal development of the package.

@mattn @blackrez @diegobernardes WDYT?

**Comment by blackrez** [comment]
Sorry for the late response, I agree to change the name in effective go : "packages are given lower case, single-word names" (https://golang.org/doc/effective_go.html#names).
But I think the name should be more clear.

**Comment by blackrez** [comment]
I’m ok this proposal.

-- 
 Nabil Servais
 nabil@eml.cc



Mer 16 oct 2019, à 16:43, Olivier Wulveryck a écrit :

**Comment by rlespinasse** [comment]
Ok, I will rename it `onnx/ir`

**Comment by rlespinasse** [comment]
@owulveryck the package is renamed as proposed : **ir**

**Comment by rlespinasse** [comment]
@owulveryck I miss to force-push my commit 😄

**Pull request merged**
