### PR TITLE
add the ability to export the exprgraph for post-processing

### PR DESCRIPTION
**Pull request by owulveryck**

### CODE REVIEW

**Comment by owulveryck** [comment]
This PR depends on [PR #309](https://github.com/gorgonia/gorgonia/pull/309) of Gorgonia

**Comment by blackrez** [comment]
I try to add test for covering this pr but the results goes wrong. 

```
+       expg, err := g.GetExprGraph()
+       fmt.Println(err)
+       if err == nil{
+               t.Fatal("")
+       }
        s.apply(g, output.(*Node))
-       err := g.Run()
-       if err == nil {
+       err1 := g.Run()
+       if err1 == nil {
                t.Fatal("should raise an error because output is not a tensor nor an operation")
        }
```

**Comment by owulveryck** [comment]
What is the result?

**Comment by blackrez** [comment]
```
--- FAIL: TestGraph_badnode (0.01s)
    graph_test.go:33: should raise an error because output is not a tensor nor an operation
```

**Comment by owulveryck** [comment]
Good catch, there was actually a bug in the walking routine.

**Pull request merged**
