### PR TITLE
Fix the use of a variable on range scope

### PR DESCRIPTION
**Pull request by diegobernardes**
As is, the code isn't wrong, but if concurrency is introduced in the tests, this gonna be a problem.

### CODE REVIEW

**Comment by owulveryck** [comment]
Good catch, thank you!

**Comment by diegobernardes** [comment]
I'm having some strange errors at the Travis build. Anyone seeing the same thing?

**Comment by owulveryck** [comment]
The problem is:

```
https fetch failed: Get https://gorgonia.org/tensor?go-get=1: dial tcp 91.195.240.94:443: i/o timeout
package gorgonia.org/tensor: unrecognized import path "gorgonia.org/tensor" (https fetch: Get https://gorgonia.org/tensor?go-get=1: dial tcp 91.195.240.94:443: i/o timeout)
```

I can reproduce it locally: 
```
GOPATH=/tmp/bla go get gorgonia.org/tensor
package gorgonia.org/tensor: unrecognized import path "gorgonia.org/tensor" (https fetch: Get https://gorgonia.org/tensor?go-get=1: dial tcp 91.195.240.94:443: i/o timeout)
```

I have to check why it cannot fetch the tensor package.

**Comment by owulveryck** [comment]
This is a problem with Gorgonia, I will take care of that.

**Comment by owulveryck** [comment]
It's fixed

**Comment by diegobernardes** [comment]
This is one of the reasons I don't like Travis. The job got stuck. I can't re-run because it's in a created state, but at Travis it's already done. Also, I had to run the same test several times due to intermittent errors at `go test` 😢

**Comment by chewxy** [comment]
FWIW, I'm moving Gorgonia to github actions :
https://www.markphelps.me/2019/09/migrating-from-travis-to-github-actions/
eventually.
Travis is quite painful to deal with.
*Xuanyi Chew*
*Follow: @chewxy <https://twitter.com/chewxy> on Twitter*
*Watch: my talk on Closure Calculus -  An Alien Lambda Calculus
<https://www.youtube.com/watch?v=ogXlQf8lDD4>*
*Read:* *my blog <http://blog.chewxy.com> *

**Comment by owulveryck** [comment]
I changed the settings to disable the mandatory Travis build just to merge this PR.
I am merging it and put it back.

Well, this really gives some points in favor of Github Actions :D

**Pull request merged**
